---
- name: shutdown instance
  virt:
    name: "{{ vm_name }}"
    state: destroyed
  failed_when: false

- name: remove instance
  virt:
    name: "{{ vm_name }}"
    command: undefine
  failed_when: false

- name: find VM image path
  ansible.builtin.find:
    path: "{{ molecule_yml.driver.images_path }}"
    patterns: "{{ vm_name }}*"
  register: del_files

- name: remove VM image
  ansible.builtin.file:
    path: "{{ file.path }}"
    state: absent
  loop: "{{ del_files.files }}"
  loop_control:
    loop_var: file
